config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'main#home'
  
  post 'create', to: 'callapi#create'
  get 'response', to: 'callapi#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/responapi.rb
class Responapi < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callapi_controller.rb
class CallapiController < ApplicationController
    
    def create
        data_form = {
            operator: params['operator'],
            phone: params['phone'],
            amount: params['amount'],
        }

        callapipracti = RestApiService.new(data_form: data_form).call
        responseapi = Responapi.new
        responseapi.estado = callapipracti[:response][:data]["estado"]
        responseapi.respuesta = callapipracti[:response][:data]["respuesta"]
        responseapi.saldo = callapipracti[:response][:data]["saldo"]
        responseapi.save

        respond_to do |format|
            format.html { redirect_to response_path }
        end
        
    end
  
    def show
        @response = Responapi.all
    end
  end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def search
    
    binding.pry
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/callapi/show.html.slim
h1 Response
=@response.last.respuesta
br 
br
-@response.each do |res|
    br
    h1 history
    p "fecha: #{res.created_at.to_date} "
    p "respuesta: #{res.respuesta} "
    p "saldo: #{res.saldo} "
    p "estado: #{res.estado} "
    br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectmysql</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%=button_to "Cerrar", destroy_user_session_path, method: :delete %>
    <br>
    <br>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.slim
h1 Main#home
.container
    .row.justify-content-md-center
        = form_with url: create_path, method: :post,  html: { novalidate: "novalidate"}  do |form|
            .col-md-auto
                label for="exampleInputEmail1" Phone Number
                =form.number_field :phone, class: "form-control rounded-xl focus:ring-sy-light focus:border-sy-light border border-gray-300 text-xs xl:text-base" 
            .col-md-auto
                br
                label for="exampleInputEmail1" Operador
                =form.select :operator, options_for_select([['fc','fc'],['pc','pc']], params[:operator]),  {class: "form-select form-select-lg mb-3"} 
                br
            .col-md-auto
                br
                label for="exampleInputEmail1" Amount
                =form.number_field :amount, class: "form-control rounded-xl focus:ring-sy-light focus:border-sy-light border border-gray-300 text-xs xl:text-base"
        
            div[class="flex justify-center my-1 2xl:my-5"]
                button[class="btn btn-primary mb-2"]Apply Filter

app/views/main/search.html copy.erb
<h1>search#home</h1>
<p>Find me in app/views/main/search.html.erb</p>